### ISSUE TITLE
Freya if not Freya

### ISSUE THREAD

**Issue by Vidarls** [freya-fs/freya#181]
is there anyway to do this:

```f#
let makeFreyaIfNotFreya x = function
    | :? Freya<_> -> x
    | _                   -> Freya.init x
```

Basically I have a function that always return a Freya of something, but I want it to accept an argument that may or may not be wrapped in a Freya.

(It seems v3 machine builder does some of this magic..)

**Comment by kolektiv** [comment]
The short answer to this is "yes" but there are certainly some caveats. I'd try and avoid doing it if possible (either via a discriminated union for the two cases, or a similar approach). I've not found too many places in "normal" code where it's worth the downsides (Machine builders being one of the few!)

If you do want to do it, the approach is basically about static inference, and looks like this:

```fsharp
[<RequireQualifiedAccess>]
module SomeModule =

    type Defaults =
        | Defaults

        static member inline SomeFunction (x: Freya<SomeType>) =
            x

        static member inline SomeFunction (x: SomeType) =
            Freya.init x

    let inline defaults (a: ^a, _: ^b) =
            ((^a or ^b) : (static member SomeFunction: ^a -> Freya<SomeType>) a)

    let inline infer (x: 'a) =
        defaults (x, Defaults)
```

Calling `SomeModule.infer` on either an instance of `SomeType` or `Freya<SomeType>` will now do what you expect. However, the caveats - inlining is a bit "viral" so functions that call this will likely need to be inlined (and public). Also the function signature will now be less obvious, as it will only refer to the member constraint required.

Hopefully that's useful, it's a handy pattern in the right circumstances, but if you find it cropping up "within" code much, rather than on the edges of libraries, I'd look to see if you can restructure something to avoid the need... :smile:

**Comment by Vidarls** [comment]
Luckily this is way! too much ceremony for me to bother sprinkling all around.

I'm basically accepting any function and need to see if it is withing a Freya or not.

Currently I have to different functions, but I'll look into the DU suggestion.

Thnx :smile:
